### ISSUE TITLE
TabExtension not working in Mx6

### ISSUE THREAD

**Issue by RCatersels** [Andries-Smit/TabExtension#1]
Hello Andries,

Allthought the TabExtension passes the deprecation test I still have an error when I put this widget in my model. I get an TypeError: mendix.addon is undefined error when starting the model which lead to a blank screen in the startpage. See the screenshot. I hope you have time to take a look at it.

Regards,

Ronald

![2016-05-12 10_49_21-tabextensionerror](https://cloud.githubusercontent.com/assets/10200344/15209070/5fef987a-182f-11e6-9e3c-f19ffda127c9.png)

**Comment by Andries-Smit** [comment]
Will check and update soon.

2016-05-12 10:52 GMT+02:00 Ronald Catersels <notifications@github.com>:

**Comment by Andries-Smit** [comment]
Hi Ronald,

Please verify if this upgrade is working for you too
https://github.com/Andries-Smit/TabExtension/blob/master/dist/2.1.0/TabExtension.mpk

Cheers, Andries

**Comment by RCatersels** [comment]
Thanks for the quick fix. Will test today.

Regards,

Ronald

**Comment by Andries-Smit** [comment]
Finished, long time ago : D
