### ISSUE TITLE
Mx8 compatible

### ISSUE THREAD

**Issue by bartrikers** [Andries-Smit/TabExtension#11]
Hi,

This widget seems to break in Mx8. When it is included on a page, the app doesn't open anymore at all...

Kind regards,
Bart Rikers

**Comment by bartrikers** [comment]
Created a quick fix, see https://github.com/Andries-Smit/TabExtension/pull/12

**Comment by tmisker** [comment]
Thanks Bart. I can confirm your fix works! I hope this leads to a new release for the Appstore.

**Comment by RCatersels** [comment]
Thanks Bart. Strange that there is still no official new version. Dynamic tab names can not be solved another way so this widget is still very valuable.

**Comment by Andries-Smit** [comment]
Will be release in v3.0.2 soon https://github.com/Andries-Smit/TabExtension/releases/tag/v3.0.2

**Comment by Andries-Smit** [comment]
Release in version v4.0.0 https://appstore.home.mendix.com/link/app/894/
