### ISSUE TITLE
Custom CSS class is not getting applicable for Tab Name widget

### ISSUE THREAD

**Issue by srangisetti** [Andries-Smit/TabExtension#13]
Hi Andries,

I have imported latest version of Tab extension widget to display tab name dynamically. I need to do styling for this and tried by using my custom css class but it is not getting affected. I also tried importing earlier versions and had the same issue . Please suggest a solution for this issue.
Thanks.

**Comment by Andries-Smit** [comment]
Dear srangisetti,

This widget, does set the style and class in the widget itself (Tab extension), and does not set the styling onto the targeted Tab.

You could add a class to the Mendix Tab widget (not this one), and use CSS selector to apply the styling to tab you require to style.

Cheers, Andries
