### ISSUE TITLE
Tab name showing on wrong tab

### ISSUE THREAD

**Issue by RCatersels** [Andries-Smit/TabExtension#2]
Hello Andries,

I know we have some complex pages but I think I have found a bug when certain tabs are hidden.
See the attached screenshots below.
I have 11 tabs on a form. Tab 8 and 9 are hidden and I have the widget on the first 7 tabs. The problem is that the text of tab 6 and 7 are displayed on tab 10 and 11. The original tab name is without the 2 next to the name. As you can see from the screenshot Pop-formulier and Feedback are not overwritten while does labels end up on the tab Competentie score and the tab Open vragen.
Could there be a bug in finding the right tab when tabs ar hidden?

Regards,

Ronald

![mendixpagewithhiddentabs](https://cloud.githubusercontent.com/assets/10200344/15327657/868a052a-1c52-11e6-87fb-c26bb4d47d99.png)
![mendixpagewithhiddentabs result](https://cloud.githubusercontent.com/assets/10200344/15327660/8a17a8aa-1c52-11e6-90ec-b3b1990e1177.png)

**Comment by Andries-Smit** [comment]
Hi Ronald,

I have update the project with a show/hide tast case, but was not able to reproduce your issue.

Could you please try to replicate your issue in the latest test project?
https://github.com/Andries-Smit/TabExtension/tree/master/test/Mx6.3.1

With kind regards, Andries

**Comment by RCatersels** [comment]
Here the adjusted demo. The problem is when I have a tab container and place another tab container inside one of the tabs. Goto Tab_Name form and take a look at tab Page 7. Because of the second container here the widget goes off track. Hope you can find a work around.

Regards,

Ronald

[TestProject_TabExtension.zip](https://github.com/Andries-Smit/TabExtension/files/270504/TestProject_TabExtension.zip)

**Comment by RCatersels** [comment]
And the widget does not have to be in the sub tabcontainer for the bug to show. Just placing an extra tabcontainer inside a tabcontainer using this widget will give this bug.

**Comment by Andries-Smit** [comment]
Just found what was causing the issue, will provide an update after the
weekend.

Cheers

2016-05-19 9:07 GMT+02:00 Ronald Catersels <notifications@github.com>:

**Comment by RCatersels** [comment]
Remind me to buy you a beer at Mendix world :)

**Comment by Andries-Smit** [comment]
Did some rework on the widget today, but can remember if i solved this issue already, did I?

**Comment by Andries-Smit** [comment]
No feedback, created new release.
