### ISSUE TITLE
Use template text with placeholders

### ISSUE THREAD

**Issue by axelbrink** [Andries-Smit/TabExtension#3]
It would be great if it would be possible to specify a template text with placeholders, such as "Attachments ({1})".

**Comment by Andries-Smit** [comment]
I do like your thinking!

**Comment by axelbrink** [comment]
I have taken the liberty to make a simple modification that allows a single replacement. If the original tab caption contains "{1}", only that will be replaced by the attribute value. Is it OK if I share this with you via a pull request?

**Comment by Andries-Smit** [comment]
Yes, please! 
Even without any changes you can reach the same result, by using a calculated value as name for the Tab.

**Comment by Andries-Smit** [comment]
Implemented

**Comment by axelbrink** [comment]
Great.

Axel.

Op 23 aug. 2016 10:01 schreef "Andries Smit" <notifications@github.com>:
