### ISSUE TITLE
Widget not working in Mx 7.1.1

### ISSUE THREAD

**Issue by amadeobrands** [Andries-Smit/TabExtension#7]
In Mendix 7 the tabs are not found by the widget see screenshot.
Is there any fix for this?
Thank you.

![2017-08-21 10_55_44-aurum brothers main line - mendix modeler 7 1 1 - c__users_amadeobrands_docume](https://user-images.githubusercontent.com/6133031/29511383-5bcfd33c-865f-11e7-9942-0ee94af2bcc7.png)

**Comment by Andries-Smit** [comment]
Project seems to work on 7.16
Please re-open if this issue is till relevant
