### ISSUE TITLE
Title property is being set to span property. I.e "<span class = "badge">9</span>"

### ISSUE THREAD

**Issue by worthingtonte** [Andries-Smit/TabExtension#8]
Hi.

When using the widget the hover title is being set on class tab-pane mx-tabcontainer-pane for id mxui_widget_TabContent_1. Which means all content in the tab on hover is showing the span of the attribute.
![screenshotexample](https://user-images.githubusercontent.com/13114839/36386183-ce45bd5c-158c-11e8-8c66-ed3ca78eb039.png)

Thanks,

Tom

**Comment by Andries-Smit** [comment]
Will be fix in the next release 3.0.1, see Mendix app store
